import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/utils/context/NextAuthProvider";
import { EdgeStoreProvider } from "./libs/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={inter.className}>
        <NextAuthProvider>
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
